version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: keiyakusho-postgres
    environment:
      POSTGRES_USER: keiyakusho
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: keiyakusho_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U keiyakusho -d keiyakusho_db']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
